### ISSUE TITLE
Requesting to cite and honour the original content creator.

### ISSUE THREAD

**Issue by markroxor** [Madhu009/Medium_Machine_learning_Blog#1]
Hello,
I am a avid follower of @sentdex and his work at [pythonprogramming.net](https://pythonprogramming.net). This guy puts on a lot of effort creating his videos and content. 

I saw your post [Chapter 3.1 : SVM from Scratch in Python.](https://medium.com/deep-math-machine-learning-ai/chapter-3-1-svm-from-scratch-in-python-86f93f853dc) where you have explained svm from scratch along with [this code](https://github.com/Madhu009/Deep-math-machine-learning.ai/blob/master/SVM-FromScratch.ipynb). I see a uncanny resemblance between his code and yours.

I request you to either cite his [website](pythonprogramming.net) or come up with your own version of "SVM from scratch".
Thank you.

**Comment by Madhu009** [comment]
Well, I am happy to mention it, actually  I pushed the code long ago, that time I couldn't think of it

**Comment by markroxor** [comment]
Great.
